### ISSUE TITLE
Программа не находит игру, добавленную в каталог 

### ISSUE THREAD

**Issue by 2Evgen** [2Evgen/TeamProject#1]
**Описание:**
Метод https://github.com/2Evgen/TeamProject/blob/64403d0fccea8f676ab48f6bece1ca915fce156c/src/main/java/ru/netology/GameStore.java#L32 не возвращает true при валидном поиске в каталоге с единственной игрой.
При не валидном поиске в каталоге с единственной игрой, метод containsGame() срабатывает верно и возвращает false.

**Локация дефекта:**
https://github.com/2Evgen/TeamProject/blob/64403d0fccea8f676ab48f6bece1ca915fce156c/src/main/java/ru/netology/GameStore.java#L32-L39

**Шаги воспроизведения:**
**1.** Открыть класс https://github.com/2Evgen/TeamProject/blob/master/src/main/java/ru/netology/GameStore.java
**2.** Запустить тест https://github.com/2Evgen/TeamProject/blob/cfae569ebe196830dbbb8ffc9258b9b056f018ad/src/test/java/ru/netology/GameStoreTest.java#L126

**Ожидаемый результат:** true
**Фактический результат:** false

**Вывод в консоли:**
org.opentest4j.AssertionFailedError: 
Expected :true
Actual   :false

**Скриншот:**
![Безымянный](https://user-images.githubusercontent.com/107884351/189726558-79740890-7596-42a5-bfb1-1119a5945fa2.png)

**Окружение:**

Операционная система Windows 8
IDE IntelliJ IDEA Community Edition 2022.1.3
Java OpenJDK 11

**Comment by MaksimNosov** [comment]
Исправлено
![Issue 1](https://user-images.githubusercontent.com/107512780/190921855-83b1891f-cbcd-4088-86b2-3fa90c26606f.jpg)
