### ISSUE TITLE
Программа суммируя игровое время игроков, возвращает ноль

### ISSUE THREAD

**Issue by 2Evgen** [2Evgen/TeamProject#3]
**Описание:**
В тестах с разным состоянием системы (с одним игроком и несколькими игроками) метод https://github.com/2Evgen/TeamProject/blob/a4b25a0891413b53775fa4f9ec75c7082219c110/src/main/java/ru/netology/GameStore.java#L75 возвращает ноль.

**Локация дефекта:**
https://github.com/2Evgen/TeamProject/blob/a4b25a0891413b53775fa4f9ec75c7082219c110/src/main/java/ru/netology/GameStore.java#L75-L77

**Шаги воспроизведения:**

1. Открыть класс 
2. Запустить тест

**Ожидаемый результат:** 60 и 190
**Фактический результат:** 0

**Вывод в консоли:**
```
org.opentest4j.AssertionFailedError: 
Expected :60
Actual   :0
```
и
```
org.opentest4j.AssertionFailedError: 
Expected :190
Actual   :0
```

**Скриншоты:**
Тест с несколькими игроками
![скин1](https://user-images.githubusercontent.com/107884351/189978139-017dd96a-81a2-477c-8039-75903e93d65e.png)
Тест  с одним игроком
![скрин](https://user-images.githubusercontent.com/107884351/189978088-8728b440-fdbe-471a-b4a5-7714509eb88d.png)

**Окружение:**

Окружение:

- 
- Операционная система Windows 8
- IDE IntelliJ IDEA Community Edition 2022.1.3
- Java OpenJDK 11

**Comment by MaksimNosov** [comment]
Исправлено
![Issue 2 1](https://user-images.githubusercontent.com/107512780/190922010-f3a3bcc9-791b-4d50-9c97-f7733dcc326d.jpg)
![Issue 2 2](https://user-images.githubusercontent.com/107512780/190922014-3a83ddae-eb24-4276-b497-51600efeccfb.jpg)
