### ISSUE TITLE
Если время игроков равно, программа выводит только одного из них 

### ISSUE THREAD

**Issue by 2Evgen** [2Evgen/TeamProject#4]
В случаи равенства двух или более лучших игроков по игровому времени, метод https://github.com/2Evgen/TeamProject/blob/a4b25a0891413b53775fa4f9ec75c7082219c110/src/main/java/ru/netology/GameStore.java#L58  возвращает только одного из них. 

 **Локация дефекта**
https://github.com/2Evgen/TeamProject/blob/a4b25a0891413b53775fa4f9ec75c7082219c110/src/main/java/ru/netology/GameStore.java#L58-L69

**Шаги воспроизведения:**

1. Открыть класс GameStoreTest 

2. Запустить тест 

**Ожидаемый результат:** метод вернет массив имен лучших игроков
**Фактический результат:** метод может вернуть только одного лучшего игрока

**Вывод в консоли:** 
```

org.opentest4j.AssertionFailedError: 
Expected :true
Actual   :false]
```

**Окружение:**

Операционная система Windows 8
IDE IntelliJ IDEA Community Edition 2022.1.3
Java OpenJDK 11

**Comment by MaksimNosov** [comment]
Исправлено
![issue 33](https://user-images.githubusercontent.com/107512780/191256247-03c26f0e-6134-4d4a-9b1a-89bf86fb1a5f.jpg)
