### ISSUE TITLE
Метод play не суммирует количество сыгранных часов

### ISSUE THREAD

**Issue by MaksimNosov** [2Evgen/TeamProject#5]
# Описание 
В описании метода указано, что он "...возвращает суммарное количество часов, проигранное в эту игру...". В текущем виде метод этого не делает

# Локация дефекта
https://github.com/2Evgen/TeamProject/blob/a4b25a0891413b53775fa4f9ec75c7082219c110/src/main/java/ru/netology/Player.java#L36

# Шаги воспроизведения
1. Открыть код программы в IDEA
1. Открыть класс с тестом к методу 
1. Запустить тест
1. Посмотреть на вывод в консоли

*Ожидаемый результат:* тест пройден, метод возвращает суммарное количество часов, проигранное в эту игру
*Фактический результат:* тест завален

# Скриншот
![Баг 1](https://user-images.githubusercontent.com/107512780/190721499-161e7e59-6a91-4174-9cf7-99689c963f0b.jpg)

# Окружение
* **Операционная система:**" Windows 10
* **IDE** IntelliJ IDEA Community Edition 2022.1.3
* **JAVA** jdk-11.0.15.10-hotspot

**Comment by 2Evgen** [comment]
https://github.com/2Evgen/TeamProject/blob/c1f612b4d5bd02b03c163faacf10c82ea65c434c/src/main/java/ru/netology/Player.java#L42
