### ISSUE TITLE
Метод play не выбрасывает сообщение об ошибке

### ISSUE THREAD

**Issue by MaksimNosov** [2Evgen/TeamProject#6]
# Описание 
В описании метода указано, что он "...если игра не была установлена, то надо выкидывать RuntimeException..". В текущем виде метод этого не делает

# Локация дефекта
https://github.com/2Evgen/TeamProject/blob/a4b25a0891413b53775fa4f9ec75c7082219c110/src/main/java/ru/netology/Player.java#L33-L41

# Шаги воспроизведения
1. Открыть код программы в IDEA
1. Открыть класс с тестом к методу 
1. Запустить тест
1. Посмотреть на вывод в консоли

*Ожидаемый результат:* тест пройден, ошибка ловится
*Фактический результат:* тест завален

# Скриншот
![Баг 2](https://user-images.githubusercontent.com/107512780/190724542-1f106e0c-7c5f-4ba2-9706-f02911cb3332.jpg)

# Окружение
* **Операционная система:**" Windows 10
* **IDE** IntelliJ IDEA Community Edition 2022.1.3
* **JAVA** jdk-11.0.15.10-hotspot

**Comment by 2Evgen** [comment]
https://github.com/2Evgen/TeamProject/blob/c1f612b4d5bd02b03c163faacf10c82ea65c434c/src/main/java/ru/netology/Player.java#L39
