### ISSUE TITLE
Метод "mostPlayerByGenre" не наполнен кодом

### ISSUE THREAD

**Issue by MaksimNosov** [2Evgen/TeamProject#8]
# Описание 
Метод "mostPlayerByGenre" не наполнен кодом, присутствует только заготовка, которая не выполняет требования по функционалу

# Локация дефекта
https://github.com/2Evgen/TeamProject/blob/a4b25a0891413b53775fa4f9ec75c7082219c110/src/main/java/ru/netology/Player.java#L59-L61

# Шаги воспроизведения
1. Открыть код программы в IDEA
1. Открыть класс Player

*Ожидаемый результат:* код метода написан, работоспособность можно проверить тестом
*Фактический результат:* код метода отсутствует

# Скриншот
нет

# Окружение
* **Операционная система:**" Windows 10
* **IDE** IntelliJ IDEA Community Edition 2022.1.3
* **JAVA** jdk-11.0.15.10-hotspot

**Comment by 2Evgen** [comment]
https://github.com/2Evgen/TeamProject/blob/c1f612b4d5bd02b03c163faacf10c82ea65c434c/src/main/java/ru/netology/Player.java#L67-L76
