### ISSUE TITLE
Gamestore.addPlayTime не суммирует значение времени игрока

### ISSUE THREAD

**Issue by 2Evgen** [2Evgen/TeamProject#9]
# **Описание** 
Метод addPlayTime, в классе Gamestore, не суммирует время игрока после его дополнительного вызова.

# **Локация дефекта**
https://github.com/2Evgen/TeamProject/blob/a4b25a0891413b53775fa4f9ec75c7082219c110/src/main/java/ru/netology/GameStore.java#L46-L51

**Шаги воспроизведения**

1. Открыть Тест-класс класса GameStore  в IDEA
2. Запустить тест shouldRegisteredAddPlayTime
3. Посмотреть на результат теста в консоли

**Ожидаемый результат:** Результат теста - "A", время просуммировалось, метод getMostPlayer вернул значение имени игрока.
**Фактический результат:** Результат теста - null, Метод getMostPlayer не нашел игрока со временем больше чем 1 час.
 **Скриншот:**
![жд](https://user-images.githubusercontent.com/107884351/191091805-4242d6f6-ecbf-41b5-9899-685d5633eeca.png)

**Окружение:**

Операционная система Windows 8
IDE IntelliJ IDEA Community Edition 2022.1.3
Java OpenJDK 11

**Comment by MaksimNosov** [comment]
исправлено
![issue 4](https://user-images.githubusercontent.com/107512780/191259406-e9998739-b0ad-4a7e-b4ff-cd6b55d9920c.jpg)
